version: 0.0
os: linux
files:
  - source: s3://my-codedeploy-bucket-3731/index.html
    destination: /var/www/html/
  - source: s3://my-codedeploy-bucket-3731/style.css
    destination: /var/www/html/
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
